name: CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.10.2

      - name: Init environment
        run: pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest